language: ruby
rvm:
  - 2.2.1
  
deploy:
  provider: heroku
  api_key:
    secure: xzdOLXfKFN52i6T5J51woWVEPyok9dAuiBLkLQHwpE6169f6NcWEb6jfp5cvYomjT6bSnAuV0yok1aGEB1jiNtVk35MUT8KPdb9H6e8aMS/ZdKTzhEv5m9UMNBw412ZLKbrlkAqjflUZ7/l5CMC4SMLnV9IzMwboJRjijtfOwghdJe5PE5t++ijrbzqoXR9jGBh11qw34iGdYQKNRvXwIdLZDF9Rj9U02hym6oypDO4c/eMv2zVUau/xAlXGDexLNGhJVfNdzWtZqIGsGKmhc7frIbSZoQxEyclh106+fIHU605F4+ZQSCDeeTTS4k5fuoyRm9lM51OdWlBAW6rZiR8ddJDH7ZduFlBnYgONzUYQxwqR0ZOEE/FCaszoFnn8wnwZbEC8cIUtQkXvI2RBuoskkwUslwXDsJ6n8nWaQLwm/EVgsPKpqa7rqNCLNYgtb+QsVVKospqjlTIhUAoUjHZAkavPrcg/fCC4GJEm/UaRegLfJ6d6rHS+3NrBExu+5FyJmbeN4Aj/W7Egmt9xhkaoI2BiRat+ZyeERD9zm+90TKmGmTKDkOXugecZoc79aXbjPqoXffCTKzf5gacBHk62cRqer+UiVU6+Guhned6wCLFUq/zgadRMm1mGpLlAiYJsI16246QB5kl33S27U9cxy6fAKggHcJEAY/muAp8=
  app: shielded-fjord-93794
  on:
    repo: FreeThoughtHobbyist/hello_app
