language: ruby
rvm:
- 2.2.1
deploy:
  provider: heroku
  api_key:
    secure: cHAtSY8ls6NLhYkTKGfPr3Y8QwNhQ8d9eAuQTqIpQ9GWLdQ6Zqf+lTTg94UzIrz1gwH/q9G1RYAT4WPGEwb8twKT8Z2W2gjac76PabDPyFh/yXej7vRG6otNIAgyy4KyP01mFTbIuKHSvFc4qLkg5BfHr5UcptWtgFBSEHIp38PS0/dWpVPDzBziH6UOJm41DxuZzeg4s1z9fAY+LiEBztuWHTivaeiIcTduKO8c53J8w8tlmRkwBdJTW2VKZWctmVaZZWsdaDvmbjqDPNkgK7aGVSoh/3o/srs2ZCtB5YzLq5xvLBidSiUVskKoYgYIpJJMIrlAvaF9g/qgozxsc5xGuV05spLCJwZbxm2f/N2aujAp1+TfbXRfJFQJVNJTyma/gk8Khl5IDWtGTEPjE9FVblnMKkiDqnzIlQPwXdTa2ADZgyL3VanuEfjdhf2/kJSQZMd8o8ljjmvrkljuFLphF9vXi6gMqsdKROYNlpP+7sSeHxnQfZOq3UZfgkE4/CsS2MIVhN8IYlsJ/WZzsozdQ1FUOVVSup/HhJaZrznsnG8MgVz0Fd+QafVtiyWW9QXQ6YJD0otQ03pC4ntyRhMIcRCf6+RqXl+ycWFsPyJJZ98dV8vEwJMPOlCQJ+pOvwynah2ue4t3doCJFkgPLGZpsE+G3KB3vnmA1GeODAQ=
